### ISSUE TITLE
Literals are broken for quasiqoutes 

### ISSUE THREAD

**Issue by valdisxp1** [liufengyun/gestalt#17]
Literals give the actual value instead of the AST.
For example, this code currently compiles:
```scala
object macros {
  inline def five(aTree: Any): Any = meta {
    val five = q"5" //XXX five is an actual number 5, NOT the corresponding tree
    println(s"$five ${five + 3}")
     // just something so the macro will compile
     q"$aTree"
  }
}
```
When invoked, it prints "`5 8`"

**Comment by valdisxp1** [comment]
Fix is straight forward:
valdisxp1/gestalt@9da10c96c66c217c0faf3ee8c2ed5153a5ae5c37

I just need to check if other parts of `Qoute.scala` are affected

**Comment by liufengyun** [comment]
The fix makes sense, it should be like this. Does all the test pass?

**Comment by valdisxp1** [comment]
The tests pass, see linked PR
