### ISSUE TITLE
Split toolbox into StructToolbox and TypedToolbox

### ISSUE THREAD

**Issue by liufengyun** [liufengyun/gestalt#19]
As a further step to simplify macros, constrain their powers, make them solid and portable, I think it's good to split Toolbox into `StructToolbox` and `TypedToolbox`.

The split is invisible to programmers (unless they define macro helpers), so it doesn't increase cognitive load of macro writers. The only thing they need to know is the restriction of powers for different types of macros. `StructToolbox` is for annotation macros, while `TypedToolbox` is for def macros.

## StructToolbox

- API to construct any trees (but not deprecated language features)
- Only API to inspect def trees: object, class, trait, val def, method def
- No API to check type information of trees, purely syntactic

## TypedToolbox

- API to construct any trees (but not deprecated language features)
- Only API to inspect some expression trees: block, ident, select, type apply, method apply.
- API to check type information of trees, implicit resolution, type check trees

## Justification

The design space of a macro system is large. **Gestalt aims to be simple, solid and lightweight for the 80% common usage**.

a ) Assumptions on compiler implementation
-  more assumptions
-  fewer assumptions (✓) : portability & easy implementation

b ) Assumptions on macro usage
- more assumptions (✓) : 80% common cases 
- fewer assumptions

c) Features
-  more features
-  fewer features (✓) : metaprogramming is hard, restrict power, implementation solid

**Comment by liufengyun** [comment]
What do you think of this proposal, @valdisxp1 ?

**Comment by valdisxp1** [comment]
It makes sense not to handle types for annotation macros. As you previously pointed out, annotation macros are expanded on untyped trees (before the typer).
However, I feel we should not limit the TypedToolbox. A def macro could easily return an anonymous class. For example, you may want to create a macro that generates a JSON format. It would naturally expand to a new anonymous class. In practice, [Play JSON macro](https://github.com/playframework/play-json/blob/master/play-json/shared/src/main/scala/JsMacroImpl.scala#L725-L737)

Also having object, class and function definitions in a block of code makes perfect sense to me. Also what happens if the prefix is an anonymous class definition? It would be frustrating to have some tree you cannot break down into components. For example, an macro implementation of `Iterator`. If you chain calls, you may want to break up the old iterator and optimize.
```scala
usersFile.iterator.map(_.name).headOption
//could expand to
new Iterator[User]{
  val reader = usersFile.open()
  def hasNext = !reader.isEOF()
  def next = reader.readUser()
}.map(_.name).headOption
// then
new Iterator[String]{
  val reader = usersFile.open()
  def hasNext = !reader.isEOF()
  def next =  reader.readUser().name
}.headOption
// and finally
{
  val reader = usersFile.open()
  if(!reader.isEOF()){
    Some(reader.readUser().name)
  } else {
    None
  }
}
```

`StructToolbox` could be a subset of `TypedToolbox`. I.e. just excluding the type information it does not have.

**Comment by liufengyun** [comment]
@valdisxp1 Thanks for your input.

Regarding the def macros, it seems the examples you give are all about constructing trees, not inspecting trees. It's fine to construct any trees in both toolbox.

What I'm curious is if there are def macros that inspect `definition trees`. Are such use cases well founded?

**Comment by liufengyun** [comment]
According to a discussion with @valdisxp1 , we agreed that `StructToolbox` is  NOT a strict subset of `TypeToolbox`, while how much they overlap can be flexibly changed by just providing more extractors.

**Comment by liufengyun** [comment]
An example why `StructToolbox` is not a subset of `TypeToolbox` is `ObjectDef` -- we allow macro writers to inspect object definitions, but we don't want def macros to inspect object definitions or make any problematic assumptions on object definition.

**Comment by liufengyun** [comment]
I'll send a PR today. @valdisxp1  if any of your work will be influenced by this PR, I'd suggest you to wait a while.

**Comment by liufengyun** [comment]
Here is a practical macro `async` and its assumptions on the syntax:

https://github.com/scala/async/tree/master/src/test/scala/scala/async/neg

In their issue list there are other issues with what syntax supported by the macro.

It reminds me the essential difference between `compiler` and `macros`. Technically, macros are just extensions of the compiler, it seems they have no difference. This view obscures one essential difference between the two:

- compiler implements a __formal__ language -- it deals with `semantics`
- macros implements a __conventional__ use of the language -- it deals with `pragmatics`

The compiler must be rigorous and comply with _language specification_. Macros have nothing to do with language specification, macro writers consciously/unconsciously profit some practical and implicit/explicit assumptions about language usage to provide simplified notations to ease the use of language.

In this regard, it's always good for macro writers to formulate the assumptions clearly and communicate to macro users explicitly.
