### ISSUE TITLE
Quasiquotes: Lifting and Unlifting

### ISSUE THREAD

**Issue by valdisxp1** [liufengyun/gestalt#25]
It would be nice to have [lifting](http://docs.scala-lang.org/overviews/quasiquotes/lifting) and [unlifting](http://docs.scala-lang.org/overviews/quasiquotes/unlifting) support.
```scala
inline def toInt(s: String): Option[Int] = meta{
  // Currently to extract a constant value we use toolbox
  val toolbox.Lit(str: String) = s
  // With unlifting we could
  val q"${str: String}" = s
  Try {
    val num = str.toInt
    // Currently to wrap a constant value we use toolbox again
    q"Some(${toolbox.Lit(num)})"
    // With lifting that could be done easier
    q"Some($num)"
  }.getOrElse(q"None")
  // ... or even more easily if we can lift Options directly
  val option = Try (Some(str.toInt)).getOrElse(None)
  q"$option"
}
```
Where lifting really shines is collections such as `List`s and `Map`s.
```scala
val map = Map("a"->1,"b"->2."c"->3)
// Currently
val entries = map.map{ case (k,v)=> q"(${toolbox.Lit(k)},${toolbox.Lit(v)})"}
q"Map(..$entries)"
// Alternative
val builder = q"val builder = Map.builder[String,Int]"
val adds = map.map{ case (k,v)=> q"builder += (${toolbox.Lit(k)},${toolbox.Lit(v)})"}
val result = q"builder.result"
toolbox.Block(builder +: adds :+ result)
// Versus lifting
q"$map"
```

Obviously this does not limit what kind of macros you can write, but it is very convenient. Therefore, as discussed with @liufengyun, this is __low priority__.

Thoughts on implementation: 
1. To support custom lifters/unlifters `Quote.scala` will have to look into `Context.implicits`
2. It will have to handle two different cases: splicing in names(`String`) and splicing in values(`toolbox.Tree`)
```scala
q"val $name = $value"
```

**Comment by liufengyun** [comment]
Regarding lifting, do you think it's acceptable to just provide implicit converters?

**Comment by valdisxp1** [comment]
It might work, definitely worth a try. I am just concerned about the cases where it expects `Seq[toolbox.Tree]` or `Seq[Seq[toolbox.Tree]]`.

**Comment by liufengyun** [comment]
It seems we will have an issue with implicit and path dependent types. But
Dotty is going to have more flexible implicits to make it possible.

Anyway, we can always do as I did in Eden to implement it in Quasiquote, if
it doesn't violate the compiler-neutrality principle(all assumptions are in
Toolbox).

**Comment by liufengyun** [comment]
Now we removed the path-dependent toolboxes, it's easy to have implicit converters and helper constructors to do the lifting.

I'm not a fan of doing lifting/unlifting in quasiquotes, it's too much hack -- and it makes quasiquote even more opaque & obscure.

**Comment by liufengyun** [comment]
Quasiquotes have been separated into a separate library implemented as gestalt macros. The decision makes it impossible to have quasiquote patterns, as it require whitebox macros. Thus unlifting is irrelevant now. Lifting can be done easily with implicit converters.
