### ISSUE TITLE
Def macros: Cannot splice in Trees with sequence literals

### ISSUE THREAD

**Issue by valdisxp1** [liufengyun/gestalt#37]
If we pass a def macro some code that contains varargs we get a tree with a sequence literal. If we splice that tree in the result. [Typer fails at line 1022](https://github.com/liufengyun/gestalt/files/893455/stack-trace.txt).
This can be shown for a simple macro.
```scala
class plus2(val a: Int) {
  inline def apply(b: Int): Int = meta {
    q"$this.a + $b"
  }
}
// this fails the Typer
assert(new plus2(Seq(2,1).sum)(5) == 8)
// it is not related to type arguments because this also fails
case class IntList(ints: Int*){
  def sum = ints.sum
}
assert(new plus2(IntList(2,1).sum)(5) == 8)
```

By contrast the typer does not fail if the call with varargs is freshly created.
```scala
class plus2(val a: Int) {
  inline def apply(b: Int): Int = meta {
    q"Seq(1,2,3).sum + $b"
  }
}
```

**Comment by liufengyun** [comment]
I just fixed in https://github.com/liufengyun/dotty/commit/f717e1949f7efb5e59bc3cf248badb88de74c612 and published the new artifacts. Clear your local cache and it should work now.

**Comment by liufengyun** [comment]
Sorry this doesn't quite work, I've to investigate further.

https://github.com/lampepfl/dotty/pull/2196

**Comment by liufengyun** [comment]
Just had a discussion with Martin about the problem -- in Dotty currently we cannot just simply re-typecheck a typed tree, it breaks a lot of things. The standard practice to re-typecheck typed trees is to wrap them inside a `TypedSplice`, which is useless for macro writers.

AFAIK, in Scalac it's completely fine to re-typecheck trees: https://github.com/scala/scala/blob/2.12.x/src/compiler/scala/tools/nsc/typechecker/Macros.scala#L633-L659 . We'll need to wait Dotty to support the same feature.
