### ISSUE TITLE
Implementing real world macros: JSON formats

### ISSUE THREAD

**Issue by valdisxp1** [liufengyun/gestalt#41]
JSON formats are classes that convert between a JSON tree and another type.
```scala
trait Format[A] {
  def toJson(o: A): JSONType
  def fromJson(json: JSONType): Option[A]
}
```
Examples: [Play JSON](https://github.com/playframework/play-json), [Scala pickling](https://github.com/scala/pickling), [Spray JSON](https://github.com/spray/spray-json)

Play and Scala pickling uses macros to generate these formats in most cases.

Things to implement to enable these macros:
- [ ] **Inspecting a type to see what fields it has.** This becomes easier when assuming it is a case class or there is extractors and constructors in the companion object. Alternative is to use methods/fields in the type definition for extraction and the primary constructor for creations.
- [ ] **Get subtypes of a type** This is needed when generating format for a abstract type, i.e. the hierarchy not just a concrete case class. See pickling for example.

Optional:
- [ ] **Inspecting implicits available in scope where macros is invoked.** Alternative way to compose formats defined elsewhere. Enables the macro to generate formats that are missing in implicits.
- [ ] **Inspect annotations of a type** This can be used to mark fields that should not be included or for specifying custom names. Similar to what Go language does [JSON in Go](https://gobyexample.com/json). Often javascript naturally expects snake_case (my_descriptive_field) while Scala naturally expects cammelCase (myDescriptiveField).
```scala
case class MyClass(
  @JsonCustomName("a_field")
  aField: A,
  @JsonIgnoreField
  trackingDebugInfo: DebugStuff
)
```
- [ ] **Allow parenthesis-less macro definitions** Just because it is 2 characters shorter to use
```scala
implicit val myFormat = Json.format[MyClass]()
// vs
implicit val myFormat = Json.format[MyClass]
```

**Comment by xeno-by** [comment]
> Inspecting implicits available in scope where macros is invoked
Is this required as a dedicated API? I think, it should be possible to make do with emitting calls to `implicitly[...]`.

> Inspect annotations of a type
Do you mean "inspect annotations of a member"?

> `implicit val myFormat = Json.format[MyClass]`
Why not have this defined as `implicit def materializeFormat[T] = macro ...`?

**Comment by liufengyun** [comment]
@xeno-by It's possible to have it defined as the following to support materialisation:

```
implicit def materializeFormat[T] = meta { ... }
```

I'll play with the Implicit resolver to support it.

**Comment by valdisxp1** [comment]
@xeno-by @liufengyun sorry for not being clear. The code example above is the invocations of the macros.
That would make the definition
```scala
object Json{
inline def format[A] = meta{....}
//or
inline def format[A]() = meta{....}
}
```
This has nothing to do with materialization.

**Comment by liufengyun** [comment]
@valdisxp1 Thanks for clarification. It makes sense for this issue to only concern ordinary def macros, I created materialization in another issue.

**Comment by valdisxp1** [comment]
@xeno-by 

> > Inspecting implicits available in scope where macros is invoke

> Is this required as a dedicated API? I think, it should be possible to make do with emitting calls to `implicitly[...]`.

This can work. That makes the dedicated API optional. It may still be useful for having the macro generate any missing implicits, give more descriptive error messages or a minor performance difference.

> > Inspect annotations of a type

> Do you mean "inspect annotations of a member"?

A format macro is invoked **only with the type** to be converted
```scala
Json.format[MyClass]()
```

If the type is a concrete class then the macro somehow needs to look up the annotations for each of the fields. This will be then used to ignore some fields or give them a custom name in the JSON object.

If information about the modifiers is not available via type then it would require looking up the `ModuleDef`.

```scala
case class MyClass(
  @JsonCustomName("a_field")
  aField: A,
  @JsonIgnoreField
  trackingDebugInfo: DebugStuff
)
```

Reading annotations is marked **optional** because it is not a core feature of the format macro. Also the same could be accomplished with passing arguments to the macros. Just a different experience for the macro user.
```scala
object Json {
  inline def format[A](
        ignoredFields: List[String] = Nil,
        customNames: Map[String,String]=Map.empty) = meta {
    // returns errors if ignoredFields or custom names cannot be directly extracted
    //...
  }
}

case class MyClass(
  aField: A,
  trackingDebugInfo: DebugStuff
)

implicit val myClassFormat = Json.format[A](
    ignoredFields=List("trackingDebugInfo"),
    customNames=Map("aField"->"a_field"))
```

**Comment by liufengyun** [comment]
Already done.
