### ISSUE TITLE
Idea: Derived toolboxes

### ISSUE THREAD

**Issue by valdisxp1** [liufengyun/gestalt#45]
To make the interface more versatile I propose derived toolboxes.
A derived toolbox is a toolbox that 
1. does not access the compiler structures directly 
2. only calls methods on a base toolbox(`Toolbox`,`StructToolbox`,`TypedToolbox`)
3. provides a different interface or semantics

For example, there could be a toolbox that ignores ascriptions. All extractors would go through ascriptions and match on the tree inside.
Simpler example: a derived toolbox that exposes only a part of the base toolbox.

Because quasiquotes depend on context, they will even work derived toolboxes. It only needs one extra function.
```scala
def withToolbox[R,T <: Toolbox](toolbox:T)(block: T => R) = block(toolbox)

//when you want to use a different toolbox you just hide the old one in the block's scope
val terribleAscribes = q"(Some((4:Int)):Option[Int])"
val i = withToolbox(new IgnoreAscriptionsToolbox(toolbox)){
  toolbox =>
   q"Some(${toolbox.Lit(a:Int)})" = terribleAscribes
   a
}
```

**Comment by liufengyun** [comment]
I'm closing this now, as toolbox as a concept is invisible to programmers now.
