### ISSUE TITLE
Initial design of APIs to support JSON formatter

### ISSUE THREAD

**Issue by liufengyun** [liufengyun/gestalt#48]
As discussed with @valdisxp1 , following APIs will be provided by the TypeToolbox:

```Scala
type Member

def prefix(String): Type                // returns a NamedType to a TermSymbol 
def typeOf(String): Type              // returns a NamedType to a TypeSymbol
def <:(Type, Type): Boolean
def typeOf(Tree): Type
def isClass(Type): Boolean
def fields(Type): Seq[Member]    // no parent fields
def name(Member): String
def typeOf(prefix: Type, mem: Member): Type    // prefix can be null
```

1. Ignore higher-kinded types and path-dependent types for now.
2. Implicit helpers will make usage more friendly, no assumption on method names of compilers.

Edited: Use `Member` instead of `Symbol`

**Comment by xeno-by** [comment]
Sounds great! What does `def typeOf(Symbol): Type` do?

**Comment by liufengyun** [comment]
`def typeOf(symbol): Type` returns the type of a field symbol.  There's no way to get a symbol to a class definition.

In the context of path-dependent types and higher-kinded types, it should be like `def typeOf(prefix:Type, name: Symbol)`.

Maybe a better name for `Symbol` is `Field` or `Member`, which is more understandable to programmers -- "Symbol" is too abstract to be understandable:

```Scala
def typeOf(prefix: Type, mem: Member): Type
```
