### ISSUE TITLE
Separate typed tree from untyped tree

### ISSUE THREAD

**Issue by liufengyun** [liufengyun/gestalt#62]
Mixing typed trees with untyped trees cause problems in the compiler. As discussed in the meeting:

- Typed trees and untyped trees take different types
- Neither is a subtype of the other (unlike in Dotty)
- Typed trees can be wrapped in untyped trees by a special untped tree: `Splice`.
- `Splice` should be as transparent to macro writers as possible

**Comment by xeno-by** [comment]
The downsides of this approach are:
  * Different families of types that mostly duplicate each other
  * Weird names for quasiquote interpolators (because interpolators can't be qualified by normal means)
  * Possibly unwarranted cognitive burden on users

All in all, despite the downsides I think this approach has much potential. It would seem that the issues that we faced in reflect (https://github.com/scalamacros/macrology201) are simply impossible in the new design.

**Comment by liufengyun** [comment]
@xeno-by I remember you mentioned below and it's agreed:

- the return type of macro expansion is untyped tree
- user can only use quasiquote to construct untyped tree (with possible typed splices)
- user can use quasiquotes to destruct both typed trees and untyped trees

Just log down to confirm, please correct me if I were wrong.

**Comment by xeno-by** [comment]
That's how I understood our discussion as well. 

I cannot commit to big architectural things like that on the spot, but the design is very compelling, and it definitely merits experimentation.

**Comment by liufengyun** [comment]
It has an assumption on the compiler side: they must have a concept called `TypedSplice` I guess, otherwise, things will not work reliably.

**Comment by xeno-by** [comment]
Another implementation-driven decision is to have untyped quasiquotes and typed quasiquotes support different subsets of the language. In the ideal world, we would provide the users with an API that supports for loops and other syntactic sugar in typed quasiquotes.

**Comment by liufengyun** [comment]
If it simplifies something, I'd propose disallow Quasiquote as patterns
completely. It seems to me it's always easier to use extractors directly
and reliably.

**Comment by liufengyun** [comment]
As the experiment in #67 shows, quasiquote-based patterns are useful for typed trees. But in annotation macros, users usually inspect def trees which have to do with modifiers and options, in that case extractor-based patterns are better.

From the observation above, maybe we can take the following compromise:

- quasiquote construction only for untyped trees
- quasiquote patterns only for typed trees

**Comment by liufengyun** [comment]
In def macros, there is also the need to embed __untyped__ trees inside __typed__ trees, e.g. transform one pattern in the body of a method. 

In this case, it seems the enclosing typed tree has to downgrade into untyped trees completely via some non-trivial rewriting.

**Comment by liufengyun** [comment]
If we restrict that the trees passed to DefMacros cannot contain `class`, `trait`, `object` and `def` (`val` is fine),  then life is much easier -- a lot of problematic macros can be prevented in the beginning.

But I'm not sure if it's a good limitation.

**Comment by liufengyun** [comment]
Due to the use case of modifying a small piece of code in typed trees, `toolbox.type(tree: untpd.Tree)` can help to ease the problem. However, we should also allow programmers to compose typed trees for the whole scheme to work.
