### ISSUE TITLE
Design considerations of extractors

### ISSUE THREAD

**Issue by liufengyun** [liufengyun/gestalt#73]
I'll try to document some of the thoughts in the design of constructor/extractors in this issue.

## Prefer macro-structure over micro-structure

A good example is the design of `Class` and `ForYield/ForDo`. An alternative design for `Class` is to have primary constructors and templates. An alternative design for `ForYield/ForDo` is to have `For/Yield`.

The current design in gestalt is superior because they are more high-level, which will make it easier for different platform implementations. Each constructor/extractor is an assumption about some shape, it's better to have assumptions on the overall shape to minimise micro assumptions which are fragile.

For example, `ForYield/ForDo` only assumes the compiler being able to represent `for/yield` and `for/do`, while `For/Yield` assumes the compiler being able to represent the micro-structure `yield`, which could make some platform implementation more complex, while doesn't bring any benefits to meta-programmers.

The same consideration justifies the removal of _template_ and _primary constructor_: the macro-assumptions are much easier to satisfy by platforms. Meanwhile, they make usage easier. The design consideration for `InitCall` is similar.

Note that currently `import` is against this principle, they should be improved.

**Comment by liufengyun** [comment]
The design of `Apply` and `ApplyType` is also against this principle, thus can be improved from this perspective.

**Comment by valdisxp1** [comment]
I came across another example of this with `New(AnonymousClass(...))` and `New(InitCall(...))`. `New` is redundant, it does not mean anything on its own. `NewAnonymousClass(...)` and `NewInstance(...)` should work better. Will send a PR fixing new instance creation with this change soon.

**Comment by liufengyun** [comment]
@valdisxp1 A potential problem with removing `New` is that if user wants just to match `new` in a transform, they could also match the parents of a class definitions.

**Comment by liufengyun** [comment]
## Have fewer constructors and extractors

As mentioned above, each abstract constructor and extractor is an assumption on compiler. Minimise the number of constructors and extractors certainly boosts portability.

Avoid providing extractors for problematic constructs, avoid constructors for deprecated language feature, avoid/delay constructors for rare & complex language features.

A common mistake here is to support everything in the language specification.

**Comment by liufengyun** [comment]
## Design for both syntax and semantics

The design of constructors and extractors is mostly driven by syntax of the language. But syntax is not the only concern. Semantically, `f(1)` in `f(1) = 3` is not a function call. Representing the left-hand side by a functional call potentially harms portability. That justifies the introduction of `Update`, `Pat.Var`, `Pat.Ascribe`, `Pat.Tuple`, `Pat.Infix`, `Self`, `InitCall`, `NewInstance`, etc.

**Comment by liufengyun** [comment]
Close, already in the paper.
